/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drake.johnston.filemanager2;

import java.util.List;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Jason
 */
public class MainFrame extends javax.swing.JFrame {

    ArrayList<String> listOfFiles = new ArrayList<String>();
    DefaultListModel modelList = new DefaultListModel();
    
    String fileSelected;
    String name;
    String job;
    Object age;
    
    public MainFrame() {
        
        initComponents();       
        
        
        
    }
    
/**
     * Creates new form MainFrame
     */
        public void WriteFile(String fileName, String personName, String personJob, int personAge, boolean writingFromScratch){

       try{
           if(writingFromScratch){
               
                FileOutputStream file = new FileOutputStream(fileName + ".txt");
                ObjectOutputStream output = new ObjectOutputStream(file);
         
                output.writeObject(personName);
                output.writeObject(personJob);
                output.writeInt(personAge);
                output.close();  
           
           }else{
           
                FileOutputStream file = new FileOutputStream(fileName);
                ObjectOutputStream output = new ObjectOutputStream(file);
         
                output.writeObject(personName);
                output.writeObject(personJob);
                output.writeInt(personAge);
                output.close();  
               
           }
         
         
               
       
       }catch(IOException e){
           
           System.out.println("An error occured");
           e.printStackTrace();
       }    
    }
        
    public String FindSpecificFile(String fileName)
    {
        String[] pathNames;
        String file = "";
        File f = new File("F:\\Projects\\FileManager");
        
        FilenameFilter filter = new FilenameFilter() {
     
            @Override
            public boolean accept(File f, String name) {
            return name.startsWith(fileName)&& name.endsWith(".txt");
            }
            
        };
        
        pathNames = f.list(filter);
        
        for (String pathName : pathNames){
        
            file = pathName;
        }  
        
        return file;
    }
    
    public static Object[] readFile(String fileName){
        
        Object persName = new Object();
        Object persJob = new Object();
        int persAge = 0;
        
        try{
            
            FileInputStream fileStream = new FileInputStream(fileName);
            ObjectInputStream objStream = new ObjectInputStream(fileStream);
            
            persName = objStream.readObject();
            persJob = objStream.readObject();
            persAge = objStream.readInt();
            
            objStream.close();      
                                  
            
        }catch(IOException e){
            
            System.out.println("An error occured");
            e.printStackTrace();
            
        }catch (Exception e){   
            
            System.out.println("An error occured");
            e.printStackTrace();
            
        }
        
        return new Object[]{persName, persJob, persAge};
    }
    
    public DefaultListModel LookForFiles(String exstension)
    {
        String[] pathNames;
        File f = new File("F:\\Projects\\FileManager2.0");
        
        FilenameFilter filter = new FilenameFilter() {
     
            @Override
            public boolean accept(File f, String name) {
            return name.endsWith(exstension);
            }
            
        };
        
        pathNames = f.list(filter);
        
        
        for (String pathName : pathNames){
        
            System.out.println(pathName);  
            modelList.addElement(pathName);
            System.out.println(modelList); 
                       
        }  
        
        System.out.println(modelList); 
        return modelList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        addNewBtn = new javax.swing.JButton();
        checkEditBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        fileManageLbl = new javax.swing.JLabel();
        CentralPanel = new javax.swing.JPanel();
        addNewPersPanel = new javax.swing.JPanel();
        addNameField = new javax.swing.JTextField();
        namLbl = new javax.swing.JLabel();
        jobLbl = new javax.swing.JLabel();
        addJobField = new javax.swing.JTextField();
        addAgeField = new javax.swing.JTextField();
        addAgeLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        addPersBtn = new javax.swing.JButton();
        hasCompletedLbl = new javax.swing.JLabel();
        checkEditPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filesList = new javax.swing.JList<>();
        refreshBtn = new javax.swing.JButton();
        ListLbl = new javax.swing.JLabel();
        EditPanel = new javax.swing.JPanel();
        selectedFeild = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        checkPanel = new javax.swing.JPanel();
        checkNLbl = new javax.swing.JLabel();
        checkAgeLbl = new javax.swing.JLabel();
        checkJobLbl = new javax.swing.JLabel();
        editFilePanel = new javax.swing.JPanel();
        newAgeLbl = new javax.swing.JLabel();
        newNameLbl = new javax.swing.JLabel();
        newJobLbl = new javax.swing.JLabel();
        newNameField = new javax.swing.JTextField();
        newJobField = new javax.swing.JTextField();
        newAgeField = new javax.swing.JTextField();
        saveChangeBtn = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        selectedLbl = new javax.swing.JLabel();
        selectBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        SidePanel.setBackground(new java.awt.Color(0, 102, 255));
        SidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SidePanel.setForeground(new java.awt.Color(51, 51, 51));

        addNewBtn.setText("Add New Person");
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });

        checkEditBtn.setText("Check/Edit People");
        checkEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEditBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        fileManageLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fileManageLbl.setText("File Manager");

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addComponent(fileManageLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(fileManageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(addNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(checkEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        CentralPanel.setLayout(new java.awt.CardLayout());

        namLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namLbl.setText("Enter a Name for Person");

        jobLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jobLbl.setText("Enter a Job for Person");

        addAgeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addAgeLbl.setText("Enter a Age for Person");

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLbl.setText("Add A Person");

        addPersBtn.setText("Press to Add Person");
        addPersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersBtnActionPerformed(evt);
            }
        });

        hasCompletedLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout addNewPersPanelLayout = new javax.swing.GroupLayout(addNewPersPanel);
        addNewPersPanel.setLayout(addNewPersPanelLayout);
        addNewPersPanelLayout.setHorizontalGroup(
            addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewPersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addNewPersPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewPersPanelLayout.createSequentialGroup()
                        .addComponent(jobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(addJobField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewPersPanelLayout.createSequentialGroup()
                        .addComponent(addAgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(addAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNewPersPanelLayout.createSequentialGroup()
                        .addComponent(namLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131)
                .addGroup(addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hasCompletedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        addNewPersPanelLayout.setVerticalGroup(
            addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewPersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJobField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(hasCompletedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewPersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        CentralPanel.add(addNewPersPanel, "card2");

        filesList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        filesList.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(filesList);

        refreshBtn.setText("Refresh List");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        ListLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListLbl.setText("List Of Current Files");

        selectedFeild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedFeildActionPerformed(evt);
            }
        });

        checkButton.setText("Check Info");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit File");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.CardLayout());

        checkPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        checkNLbl.setText("Name:");

        checkAgeLbl.setText("Age:");

        checkJobLbl.setText("Job:");

        javax.swing.GroupLayout checkPanelLayout = new javax.swing.GroupLayout(checkPanel);
        checkPanel.setLayout(checkPanelLayout);
        checkPanelLayout.setHorizontalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkNLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(checkAgeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkJobLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        checkPanelLayout.setVerticalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkJobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(checkPanel, "card2");

        editFilePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        newAgeLbl.setText("New Age");
        newAgeLbl.setToolTipText("leave blank to leave the same");

        newNameLbl.setText("New Name");
        newNameLbl.setToolTipText("leave blank to leave the same");

        newJobLbl.setText("New Job");
        newJobLbl.setToolTipText("leave blank to leave the same");

        saveChangeBtn.setText("Save Changes");
        saveChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editFilePanelLayout = new javax.swing.GroupLayout(editFilePanel);
        editFilePanel.setLayout(editFilePanelLayout);
        editFilePanelLayout.setHorizontalGroup(
            editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFilePanelLayout.createSequentialGroup()
                .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editFilePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newJobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newAgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newJobField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editFilePanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(saveChangeBtn)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        editFilePanelLayout.setVerticalGroup(
            editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFilePanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newJobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newJobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(saveChangeBtn))
        );

        jPanel2.add(editFilePanel, "card3");

        deleteButton.setText("Delete File");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        selectedLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedLbl.setText("Selected File: ");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditPanelLayout.createSequentialGroup()
                        .addComponent(checkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addComponent(selectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectedFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectBtn.setText("Select File");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkEditPanelLayout = new javax.swing.GroupLayout(checkEditPanel);
        checkEditPanel.setLayout(checkEditPanelLayout);
        checkEditPanelLayout.setHorizontalGroup(
            checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkEditPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkEditPanelLayout.createSequentialGroup()
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshBtn)
                        .addContainerGap(517, Short.MAX_VALUE))
                    .addGroup(checkEditPanelLayout.createSequentialGroup()
                        .addGroup(checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        checkEditPanelLayout.setVerticalGroup(
            checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkEditPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(checkEditPanelLayout.createSequentialGroup()
                        .addComponent(ListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn)
                    .addComponent(selectBtn))
                .addGap(77, 77, 77))
        );

        CentralPanel.add(checkEditPanel, "card3");

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CentralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CentralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEditBtnActionPerformed
        // TODO add your handling code here:
        System.out.print("Pressed Edit");
        
        checkEditPanel.setVisible(true);
        addNewPersPanel.setVisible(false);
        
        MainFrame mF = new MainFrame();
        
        filesList.setModel(mF.LookForFiles(".txt"));
        System.out.println(modelList);
        
    }//GEN-LAST:event_checkEditBtnActionPerformed

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        // TODO add your handling code here:
        System.out.print("Pressed Add");
        
        checkEditPanel.setVisible(false);
        addNewPersPanel.setVisible(true);
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void addPersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersBtnActionPerformed
        // TODO add your handling code here:
        MainFrame mF = new MainFrame();
        String perJob = addJobField.getText();
        String perName = addNameField.getText();
        int perAge = Integer.parseInt(addAgeField.getText());
        String fileName = perName + "_" + perJob;
        
        mF.WriteFile( fileName, perName, perJob, perAge, true);
    }//GEN-LAST:event_addPersBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        MainFrame mF = new MainFrame();
        
        filesList.setModel(mF.LookForFiles(".txt"));
        System.out.println(modelList);

    }//GEN-LAST:event_refreshBtnActionPerformed

    
    
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void selectedFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedFeildActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        fileSelected = (String) filesList.getSelectedValue();
        selectedFeild.setText(fileSelected);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        if(fileSelected != ""){
            editFilePanel.setVisible(false);
            checkPanel.setVisible(true);

            MainFrame mF = new MainFrame();
            Object[] person = readFile(fileSelected);
            checkNLbl.setText("Person Name: " + person[0].toString());
            checkJobLbl.setText("Person Job: " + person[1].toString());
            checkAgeLbl.setText("Person Age: " + person[2].toString());
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        editFilePanel.setVisible(true);
        checkPanel.setVisible(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeBtnActionPerformed
        // TODO add your handling code here:
        MainFrame mF = new MainFrame();
        Object[] person = readFile(fileSelected);
        
        name = person[0].toString();
        job = person[1].toString();
        age = person[2];
        
        if(newNameField.getText() == "")
        {
            name = person[0].toString();
        }else{
            
            name = newNameField.getText();
        
        }
        
        if(newJobField.getText() == "")
        {
            
            job = person[1].toString();
            
        }else{
            
            job = newJobField.getText();
        
        }
        
        if(newAgeField.getText() == "")
        {
            
            age = person[2];
            
        }else{
            
            age = Integer.parseInt(newAgeField.getText());
        
        }
        
        String fileName = name + "_" + job;
        File f = new File("E:\\Projects\\FileManager2.0\\" + fileSelected);  
        f.delete();
        mF.WriteFile(fileName, name, job, (int) age, true);           
    }//GEN-LAST:event_saveChangeBtnActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(fileSelected != ""){
        
            File f = new File("F:\\Projects\\FileManager2.0\\" + fileSelected);
            f.delete();
            MainFrame mF = new MainFrame();
        
            filesList.setModel(mF.LookForFiles(".txt"));
            System.out.println(modelList);
            
            selectedFeild.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralPanel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JLabel ListLbl;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTextField addAgeField;
    private javax.swing.JLabel addAgeLbl;
    private javax.swing.JTextField addJobField;
    private javax.swing.JTextField addNameField;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JPanel addNewPersPanel;
    private javax.swing.JButton addPersBtn;
    private javax.swing.JLabel checkAgeLbl;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton checkEditBtn;
    private javax.swing.JPanel checkEditPanel;
    private javax.swing.JLabel checkJobLbl;
    private javax.swing.JLabel checkNLbl;
    private javax.swing.JPanel checkPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel editFilePanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel fileManageLbl;
    private javax.swing.JList<String> filesList;
    private javax.swing.JLabel hasCompletedLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLbl;
    private javax.swing.JLabel namLbl;
    private javax.swing.JTextField newAgeField;
    private javax.swing.JLabel newAgeLbl;
    private javax.swing.JTextField newJobField;
    private javax.swing.JLabel newJobLbl;
    private javax.swing.JTextField newNameField;
    private javax.swing.JLabel newNameLbl;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton saveChangeBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextField selectedFeild;
    private javax.swing.JLabel selectedLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
